// aluno 
const INCREMENTAR_TEMPO ="aluno/INCREMENTAR_TEMPO";
const REDUZIR_TEMPO = "aluno/REDUZIR_TEMPO";
const REDUZIR_TEMPO_AULA = "aluno/REDUZIR_TEMPO_AULA";
const MODIFICAR_EMAIL = "aluno/MODIFICAR_EMAIL";
const COMPLETAR_AULA ="aluno/COMPLETAR_AULA";
const COMPLETAR_CURSO = "aluno/COMPLETAR_CURSO";
const RESETAR_CURSO = "aluno/RESETAR_CURSO";

export const Consts = {
  INCREMENTAR_TEMPO,
  REDUZIR_TEMPO,
  REDUZIR_TEMPO_AULA,
  MODIFICAR_EMAIL,
  COMPLETAR_AULA ,
  COMPLETAR_CURSO,
  RESETAR_CURSO
}